# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HyperTiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import numpy as np
import itertools
import math
import colorsys
from scipy.spatial.distance import _distance_wrap

class Ui_MainWindow(object):
    ##here we're setting up the whole GUI
    def setupUi(self, MainWindow):
        ##first we set the size of the main window, which is fixed - picked these for aesthetics and to allow square windows
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        ##don't allow stretching (for now) - potential to add this once you've figured out what you're doing
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 800))

        ##add our main widget to the main window
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        ##set up our horizontal layout (to split the window into the 2 sections)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        ##add our parameter section to the layout, style it, and name it
        self.parameterArea = QtWidgets.QFrame(self.centralwidget)
        self.parameterArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameterArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameterArea.setObjectName("parameterArea")

        ##split the parameter section into 2 vertical sections, set the margins
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.parameterArea)
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        ##create our graphics view for the vectors, set the parameters and sizes, and add its name before adding it to our first vertical layout
        # self.vectorPlot = QtWidgets.QGraphicsView(self.parameterArea)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.vectorPlot.sizePolicy().hasHeightForWidth())
        # self.vectorPlot.setSizePolicy(sizePolicy)
        # self.vectorPlot.setMinimumSize(QtCore.QSize(288, 288))
        # self.vectorPlot.setMaximumSize(QtCore.QSize(288, 288))
        # self.vectorPlot.setObjectName("vectorPlot")
        # self.verticalLayout_3.addWidget(self.vectorPlot)
        self.vectorPlot = pg.PlotWidget(self.parameterArea)
        self.vectorPlot.setObjectName("vectorPlot")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vectorPlot.sizePolicy().hasHeightForWidth())
        self.vectorPlot.setSizePolicy(sizePolicy)
        self.vectorPlot.setMinimumSize(QtCore.QSize(288, 288))
        self.vectorPlot.setMaximumSize(QtCore.QSize(288, 288))
        self.vectorPlot.setObjectName("vectorPlot")
        self.verticalLayout_3.addWidget(self.vectorPlot)

        self.vectorPlot.setBackground('w')
        # self.vectorPlot.setLimits(xMin = -5)
        # self.vectorPlot.setLimits(xMax = 105)
        # self.vectorPlot.setLimits(yMin = -5)
        # self.vectorPlot.setLimits(yMax = 105)
        self.vectorPlot.getPlotItem().hideAxis('bottom')
        self.vectorPlot.getPlotItem().hideAxis('left')
        self.vectorPlot.hideButtons()

        ##add a spacer to neaten things up between the vector plot area and the tiling parameter section
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem)

        ##add our tiling parameter group to our parameter box, set the margins and name
        self.tilingParameters = QtWidgets.QVBoxLayout()
        self.tilingParameters.setObjectName("tilingParameters")
        self.parameterGroup = QtWidgets.QGroupBox(self.parameterArea)
        self.parameterGroup.setObjectName("parameterGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.parameterGroup)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        ##add our presets, labels and selections for parameters
        # self.presetBox = QtWidgets.QHBoxLayout()
        # self.presetBox.setObjectName("presetBox")
        # self.presetLabel = QtWidgets.QLabel(self.parameterGroup)
        # self.presetLabel.setObjectName("presetLabel")
        # self.presetBox.addWidget(self.presetLabel)
        # self.presetSelect = QtWidgets.QComboBox(self.parameterGroup)
        # self.presetSelect.setObjectName("presetSelect")
        # self.presetSelect.addItem("")
        # self.presetSelect.addItem("")
        # self.presetSelect.addItem("")
        # self.presetSelect.addItem("")
        # self.presetBox.addWidget(self.presetSelect)
        # spacerItem1 = QtWidgets.QSpacerItem(70, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        # self.presetBox.addItem(spacerItem1)
        # self.verticalLayout_4.addLayout(self.presetBox)
        # self.presetSelect.textActivated.connect(self.presetChange)

        ##add our parameters neatly - first, symmetry
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.symmetryBox = QtWidgets.QHBoxLayout()
        self.symmetryBox.setObjectName("symmetryBox")
        self.symmetryLabel = QtWidgets.QLabel(self.parameterGroup)
        self.symmetryLabel.setObjectName("symmetryLabel")
        self.symmetryBox.addWidget(self.symmetryLabel)
        self.symmetryValue = QtWidgets.QSpinBox(self.parameterGroup)
        self.symmetryValue.setObjectName("symmetryValue")
        self.symmetryBox.addWidget(self.symmetryValue)
        spacerItem3 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.symmetryBox.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.symmetryBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.symmetryValue.setSizePolicy(sizePolicy)
        self.symmetryValue.setMinimumSize(QtCore.QSize(60, 20))
        self.symmetryValue.setMaximumSize(QtCore.QSize(60, 20))
        self.symmetryValue.valueChanged.connect(self.updateVector)
        # self.symmetryValue.act
        #TODO: consider allowing return to be pressed to tile
        

        ##then, adding the patch size
        self.sizeBox = QtWidgets.QHBoxLayout()
        self.sizeBox.setObjectName("sizeBox")
        self.sizeLabel = QtWidgets.QLabel(self.parameterGroup)
        self.sizeLabel.setObjectName("sizeLabel")
        self.sizeBox.addWidget(self.sizeLabel)
        self.sizeValue = QtWidgets.QSpinBox(self.parameterGroup)
        self.sizeValue.setObjectName("sizeValue")
        self.sizeBox.addWidget(self.sizeValue)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.sizeBox.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.sizeBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.sizeValue.setSizePolicy(sizePolicy)
        self.sizeValue.setMinimumSize(QtCore.QSize(60, 20))
        self.sizeValue.setMaximumSize(QtCore.QSize(60, 20))



        ##finally our grid shift selection
        self.gridShiftBox = QtWidgets.QHBoxLayout()
        self.gridShiftBox.setObjectName("gridShiftBox")
        self.shiftLabel = QtWidgets.QLabel(self.parameterGroup)
        self.shiftLabel.setObjectName("shiftLabel")
        self.gridShiftBox.addWidget(self.shiftLabel)
        self.shiftSelect = QtWidgets.QComboBox(self.parameterGroup)
        self.shiftSelect.setObjectName("shiftSelect")
        self.shiftSelect.addItem("")
        self.shiftSelect.addItem("")
        self.shiftSelect.addItem("")
        self.shiftSelect.addItem("")
        self.gridShiftBox.addWidget(self.shiftSelect)
        spacerItem5 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridShiftBox.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.gridShiftBox)

        ##add a spacer so there's a nice gap between parameters and the advanced button, then add the advanced button
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.advancedBox = QtWidgets.QHBoxLayout()
        self.advancedBox.setObjectName("advancedBox")
        self.advancedButton = QtWidgets.QPushButton(self.parameterGroup)
        self.advancedButton.setObjectName("advancedButton")
        self.advancedBox.addWidget(self.advancedButton)
        self.verticalLayout_4.addLayout(self.advancedBox)
        self.tilingParameters.addWidget(self.parameterGroup)

        ##finally add the tile button
        self.verticalLayout_3.addLayout(self.tilingParameters)
        self.tileButton = QtWidgets.QPushButton(self.parameterArea)
        self.tileButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.tileButton)
        self.tileButton.clicked.connect(self.pushTileButton)


        ##add a final spacer 
        spacerItem7 = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)


        ##now to the plotting area. add the horizontal layout, style it, name it        
        self.horizontalLayout.addWidget(self.parameterArea)
        self.plotArea = QtWidgets.QFrame(self.centralwidget)
        self.plotArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotArea.setObjectName("plotArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plotArea)
        self.verticalLayout.setContentsMargins(7, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        ##this is the thing we actually plot to - it's auto generated, but i think we have to change it
        # self.tilingPlot = QtWidgets.QGraphicsView(self.plotArea)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.tilingPlot.sizePolicy().hasHeightForWidth())
        # self.tilingPlot.setSizePolicy(sizePolicy)
        # self.tilingPlot.setMinimumSize(QtCore.QSize(700, 700))
        # self.tilingPlot.setMaximumSize(QtCore.QSize(700, 700))
        # self.tilingPlot.setObjectName("tilingPlot")
        # self.verticalLayout.addWidget(self.tilingPlot)


        ## to this:
        self.tilingPlot = pg.PlotWidget(self.plotArea)
        self.tilingPlot.setObjectName("tilingPlot")
        self.verticalLayout.addWidget(self.tilingPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilingPlot.sizePolicy().hasHeightForWidth())
        self.tilingPlot.setSizePolicy(sizePolicy)
        self.tilingPlot.setMinimumSize(QtCore.QSize(700, 700))
        self.tilingPlot.setMaximumSize(QtCore.QSize(700, 700))
        self.tilingPlot.setBackground('w')
        self.tilingPlot.getPlotItem().hideAxis('bottom')
        self.tilingPlot.getPlotItem().hideAxis('left')
        self.tilingPlot.hideButtons()

        ##add our buttons for plotting, editing colour, and saving
        self.plotButtons = QtWidgets.QHBoxLayout()
        self.plotButtons.setSpacing(6)
        self.plotButtons.setObjectName("plotButtons")
        spacerItem8 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.plotButtons.addItem(spacerItem8)
        self.gridView = QtWidgets.QPushButton(self.plotArea)
        self.gridView.setObjectName("gridView")
        self.plotButtons.addWidget(self.gridView)
        self.editStyle = QtWidgets.QPushButton(self.plotArea)
        self.editStyle.setObjectName("editStyle")
        self.plotButtons.addWidget(self.editStyle)
        self.saveAs = QtWidgets.QPushButton(self.plotArea)
        self.saveAs.setObjectName("saveAs")
        self.plotButtons.addWidget(self.saveAs)
        self.verticalLayout.addLayout(self.plotButtons)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.plotArea)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)

        ##go back to our centralwidget, add out menu bar and associated menus
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        ##add a bunch of default parameters here (have you plotted yet, etc.)
        self.plotted = False

        ##finally call our function which adds our text to the various objects we need
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
    
    def retranslateUi(self, MainWindow):

        ##relabel all our stuff
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.parameterGroup.setTitle(_translate("MainWindow", "Tiling parameters"))
        # self.presetLabel.setText(_translate("MainWindow", "Preset:"))
        # self.presetSelect.setItemText(0, _translate("MainWindow", "Penrose"))
        # self.presetSelect.setItemText(1, _translate("MainWindow", "Ammann-Beenker"))
        # self.presetSelect.setItemText(2, _translate("MainWindow", "Socolar Dodecagonal"))
        # self.presetSelect.setItemText(3, _translate("MainWindow", "Load preset..."))
        self.symmetryLabel.setText(_translate("MainWindow", "No. of vectors:"))
        self.sizeLabel.setText(_translate("MainWindow", "No. of grids:"))
        self.shiftLabel.setText(_translate("MainWindow", "Grid shifts:"))
        self.shiftSelect.setItemText(0, _translate("MainWindow", "Regular"))
        self.shiftSelect.setItemText(1, _translate("MainWindow", "Zero"))
        self.shiftSelect.setItemText(2, _translate("MainWindow", "Random"))
        self.shiftSelect.setItemText(3, _translate("MainWindow", "Regular random"))
        self.advancedButton.setText(_translate("MainWindow", "Advanced..."))
        self.tileButton.setText(_translate("MainWindow", "Tile!"))
        self.gridView.setText(_translate("MainWindow", "Grid view"))
        self.editStyle.setText(_translate("MainWindow", "Edit style..."))
        self.saveAs.setText(_translate("MainWindow", "Save as..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))

    def updateVector(self):
        value = self.symmetryValue.value()        
        vec_item = vectorPlotting(value)
        self.vectorPlot.clear()
        self.vectorPlot.enableAutoRange()
        self.vectorPlot.addItem(vec_item)

    def pushTileButton(self):
        #TODO: do we want this to be int? or float for fun?
        p1 = self.symmetryValue.value()
        p2 = 1#((np.sqrt(3)+1)/2) 
        p3 = 0
        p4 = 1#((np.sqrt(5)+1)/2)
        p5 = self.sizeValue.value()

        #TODO: you need to add something which checks the length of the calcs you're about to do - either as a pop up, or as some barrier 
        p6 = self.shiftSelect.currentText()#'regular' #'random'

        self.tiling = TileMaker(p1,p2,p3,p4,p5,p6)#((np.sqrt(5)+1)/2)
        # TODO: add parameters which describe the min and max areas properly
        self.tilingPlot.setLimits(xMin = -20)
        self.tilingPlot.setLimits(xMax = 20)
        self.tilingPlot.setLimits(yMin = -20)
        self.tilingPlot.setLimits(yMax = 20)

        vec_item = vectorPlotting(p1)
        self.vectorPlot.clear()
        self.vectorPlot.enableAutoRange()
        self.vectorPlot.addItem(vec_item)         

        self.poly_areas = self.tiling.poly_areas
        self.poly_areas = np.round(self.poly_areas,3)
        self.poly_unq = np.unique(self.poly_areas)
        # if the area is a whole number then it breaks here (?)
        #replace the unique area sizes with a 'key'
        for a in range(len(self.poly_unq)):
            self.poly_areas[self.poly_areas == self.poly_unq[a]] = a
        
        self.ngon_unq = []
        self.ngon_areas = self.tiling.ngon_areas
        if len(self.ngon_areas) > 0:
            
            self.ngon_areas = np.round(self.ngon_areas,3)
            self.ngon_unq = np.unique(self.ngon_areas)

            for a in range(len(self.ngon_unq)):
                ##add the length of the poly_unq as we want to add more colours to the system
                self.ngon_areas[self.ngon_areas == self.ngon_unq[a]] = a+len(self.poly_unq)
            self.ngon_areas = self.ngon_areas.astype(int)
        self.poly_areas = self.poly_areas.astype(int)
        

        color = []
        h = np.random.rand(1)[0]
        for a in range(len(self.poly_unq)+len(self.ngon_unq)):
            h += 0.618
            h %= 1

            (r, g, b) = colorsys.hsv_to_rgb(h, 0.4, 0.8)
            color.append((float(r*255), float(g*255), float(b*255)))

        poly_color = np.array(color)[self.poly_areas]
        ngon_color = np.array(color)[self.ngon_areas]

        item = tilePlot(self.tiling, poly_color, ngon_color)

        if self.plotted:
            self.tilingPlot.clear()
            self.tilingPlot.enableAutoRange()
        
        self.tilingPlot.addItem(item)
          
        self.plotted = True

    def pushEditStyleButton(self):
        if not self.plotted:
            return
        else:
            self.tilingPlot.clear()
            color = []
            h = np.random.rand(1)
            for a in range(len(self.unq)):
                h += 0.618
                h %= 1

                (r, g, b) = colorsys.hsv_to_rgb(h, 0.4, 0.8)
                color.append((float(r*255), float(g*255), float(b*255)))

            color = np.array(color)[self.areas]
            item = tilePlot(self.tiling, color)
            self.tilingPlot.addItem(item) 

    # def presetChange(self):

    #     ##when presets are changed, we find what index they've been changed to
    #     ##then assign the values you need to 
    #     preset_idx = self.presetSelect.currentIndex()
    #     if preset_idx == 0:
    #         value = 5
    #         self.symmetryValue.setValue(value)
    #     elif preset_idx == 1:
    #         value = 8
    #         self.symmetryValue.setValue(value)
    #     elif preset_idx == 2:
    #         value = 12
    #         self.symmetryValue.setValue(value) 
    #     #TODO: figure out how to load presets
    #     # elif preset_idx == 3:
    #     #     value = 12
    #     #     self.symmetryValue.setValue(value) 

    #     vec_item = vectorPlot(value)
    #     self.vectorPlot.clear()
    #     self.vectorPlot.enableAutoRange()
    #     self.vectorPlot.addItem(vec_item) 



class TileMaker:
    def __init__(self, fold, tau, ang, omega, grid_len, shift_type):

        theta = 2*np.pi/fold
        grid_vectors = []
        tile_vectors = []

        if fold == 4:
            for i in range(int(fold)):
                if (i)<2:
                    grid_vectors.append((np.cos(theta*i), np.sin(theta*i)))
                    tile_vectors.append((np.cos(theta*i), np.sin(theta*i)))

                else:
                    grid_vectors.append((omega*np.cos(ang+theta*i), omega*np.sin(ang+theta*i)))
                    tile_vectors.append(((1/tau)*np.cos(ang+theta*i), (1/tau)*np.sin(ang+theta*i)))
        else:
            for i in range(int(fold)):
                if (i)%2:
                    grid_vectors.append((np.cos(theta*i), np.sin(theta*i)))
                    tile_vectors.append((np.cos(theta*i), np.sin(theta*i)))

                else:
                    grid_vectors.append((omega*np.cos(ang+theta*i), omega*np.sin(ang+theta*i)))
                    tile_vectors.append(((1/tau)*np.cos(ang+theta*i), (1/tau)*np.sin(ang+theta*i)))


        ang = [math.atan2(x[1],x[0]) for x in grid_vectors]
        val = (np.round(ang,2)+0 >= 0).sum()
        ang = [(x+2*np.pi if np.round(x,2) < 0 else x) for x in ang]
        arg = np.argsort(ang)

        grid_vectors = np.array(grid_vectors)[arg]
        tile_vectors = np.array(tile_vectors)[arg]
        
        if shift_type == 'Regular':
            if fold % 2 ==0:
                shifts = [1/(fold/2),-1/(fold/2)]*int(fold/2)
            else:
                shifts = [1/(fold)]*fold

        if shift_type == 'Random':
            shifts = np.random.rand(fold)

        if shift_type == 'Zero':
            shifts = [0]*fold
        
        if shift_type == 'Regular random':
            r = np.random.rand(1, fold)
            r /= np.sum(r)
            shifts = r[0]
        #TODO: figure out how to pass your custom shifts here
        # if shift_type == 'custom':
        #     shifts = [0]*fold
   
        
        line_len = 100
        
        grid = Grids(grid_vectors, line_len, grid_len, shifts, val)
        gen = self.make_tile(grid, tile_vectors)
        self.points = gen[0]        
        self.p_points = gen[1]
        self.poly_areas = gen[2]
        self.ngon_areas = gen[3]

    def intersect(self, A, B, C, D):
        t = ((A[0]-C[0])*(C[1]-D[1])-(A[1]-C[1])*(C[0]-D[0]))/((A[0]-B[0])*(C[1]-D[1])-(A[1]-B[1])*(C[0]-D[0]))
        u = ((A[0]-C[0])*(A[1]-B[1])-(A[1]-C[1])*(A[0]-B[0]))/((A[0]-B[0])*(C[1]-D[1])-(A[1]-B[1])*(C[0]-D[0]))

        if (t <= 1) & (t >= 0) & (u <= 1) & (u >= 0):
            return np.asarray([[A[0]+t*(B[0]-A[0]), A[1]+t*(B[1]-A[1])]])

    def cdist(self, XA, XB, dm):
        cdist_fn = getattr(_distance_wrap, "cdist_euclidean_double_wrap")
        cdist_fn(XA, XB, dm)
        return dm

    def collinear(self, comb_list, vectors):
        indexes = []

        for a in range(len(comb_list)):
            if np.cross(vectors[comb_list[a][0]], vectors[comb_list[a][1]]) == 0:
                indexes.append(a)
        self.del_list(comb_list, indexes)
        return comb_list

    def clockwise(self, coords):
        pp = (list(zip(coords[:,0], coords[:,1])))
        cent = (sum([p[0] for p in pp]) / len(pp), sum([p[1] for p in pp]) / len(pp))
        pp.sort(key=lambda p: math.atan2(p[1]-cent[1], p[0]-cent[0]))
        return pp

    def del_list(self, _list, indexes):
        for index in sorted(indexes, reverse=True):
            del _list[index]
        return _list

    def area(self, p):
        return 0.5 * abs(sum(x0 * y1 - x1 * y0 for ((x0, y0), (x1, y1)) in self.segments(p)))

    def polygon_area(self, x, y):
        correction = x[-1] * y[0] - y[-1] * x[0]
        main_area = np.dot(x[:-1], y[1:]) - np.dot(y[:-1], x[1:])
        return 0.5 * np.abs(main_area + correction)

    def segments(self, p):
        return zip(p, p[1:] + [p[0]])

    def perp_vec(self, v):
        return (v[1], -v[0])

    def cyclic(self, size):
        j, j_step = 0, 0
        i, i_step = 1, 1

        store = []
        for a in range(size):
            idx = list(range(j, i))
            
            store.append(idx)

            if a + 1 == size / 2:
                i_step = 0
                j_step = 1
            i += i_step
            j += j_step
        return store

    def n_gon(self, index_set, grid1_idx, grid2_idx, j, k, grid, list2, val):
        indices = grid.index[0]
        angles = [grid.angles[grid1_idx], grid.angles[grid2_idx]]
        vectors = [grid.grid_vectors[grid1_idx], grid.grid_vectors[grid2_idx]]
        factor = []

        all_grids = [grid1_idx, grid2_idx]

        if grid1_idx >= val:
            index_set[grid1_idx] = indices[j]
            angles[0] = angles[0] + math.pi
            vectors[0] = (-1 * vectors[0][0], -1 * vectors[0][1])
            factor.append(-1)
        else:
            index_set[grid1_idx] = indices[j - 1]
            factor.append(1)

        if grid2_idx >= val:
            index_set[grid2_idx] = indices[k]
            angles[1] = angles[1] + math.pi
            vectors[1] = (-1 * vectors[1][0], -1 * vectors[1][1])
            factor.append(-1)
        else:
            index_set[grid2_idx] = indices[k - 1]
            factor.append(1)

        construct = self.cyclic((2 + len(list2)) * 2)

        for i in range(len(list2)):
            grid_choice = list2[i][0]
            all_grids.append(grid_choice)
            if grid_choice >= val:
                index_set[grid_choice] = indices[max(list2[i][1], list2[i][2])]
                angles.append(grid.angles[grid_choice] + math.pi)
                vectors.append((-grid.grid_vectors[grid_choice][0], -grid.grid_vectors[grid_choice][1]))
                factor.append(-1)
            else:
                index_set[grid_choice] = indices[min(list2[i][1], list2[i][2])]
                angles.append(grid.angles[grid_choice])
                vectors.append(grid.grid_vectors[grid_choice])
                factor.append(1)

        origin = index_set.copy()
        clocksort = [(x + 2 * np.pi if x < 0 else x) for x in angles]
        ang_sort = np.argsort(angles)
        all_grids = np.array(all_grids)
        all_grids = all_grids[ang_sort]
        factor = np.array(factor)
        factor = factor[ang_sort]
        store = []
        store.append(origin)

        for i in range(len(construct) - 1):
            extend = origin.copy()
            for j in range(len(construct[i])):
                extend[all_grids[construct[i][j]]] = extend[all_grids[construct[i][j]]] + factor[construct[i][j]]
            store.append(extend)

        return store

    def make_tile(self, grid, tile_vectors):
        dm = np.empty((1, grid.grid_len), dtype=np.double)
        dimension = len(grid.grid_vectors)
        ind_mult = [[1, 0], [1, 1], [0, 1]]
        vec_no = list(range(dimension))
        radius = np.ceil(grid.grid_len / 3)
        val = grid.val
        combs = self.collinear(list(itertools.combinations(list(range(dimension)), 2)), grid.grid_vectors)
        store = []
        p_store = []
        indices = [0] * dimension

        for i in range(len(combs)):
            grid1_idx = combs[i][0]
            grid2_idx = combs[i][1]
            vec_query = self.del_list(vec_no.copy(), [grid1_idx, grid2_idx])

            for j in range(1, grid.grid_len):
                for k in range(1, grid.grid_len):
                    count = 0
                    interx = self.intersect(grid.grids[grid1_idx][0][j], grid.grids[grid1_idx][1][j], grid.grids[grid2_idx][0][k], grid.grids[grid2_idx][1][k])
                    if interx is None:
                        continue
                    if interx[0][0]**2 + interx[0][1]**2 > radius**2:
                        continue
                    tile = []
                    poly = []
                    index_set = indices.copy()
                    index_set[grid1_idx] = grid.index[grid1_idx][j]
                    index_set[grid2_idx] = grid.index[grid2_idx][k]
                    poly.append(grid1_idx)
                    poly.append(grid2_idx)
                    list2 = []
                    for l in range(len(vec_query)):
                        grid_choice = vec_query[l]
                        dist = self.cdist(interx, grid.midpoints[grid_choice], dm)[0]
                        dist_idx = dist.argsort()
                        dist_sort = dist[dist_idx]
                        #TODO: think about a different, better way of doing this
                        if dist_sort[1] - dist_sort[0] < 0.00000001:
                            count = count + 1
                            poly.append(grid_choice)
                            list2.append((grid_choice, dist_idx[0], dist_idx[1]))
                        else:
                            index_set[grid_choice] = grid.index[grid_choice][dist_idx[0]]
                    if count == 0:
                        tile.append(index_set)
                        for a in range(3):
                            tile_vert = index_set.copy()
                            tile_vert[grid1_idx] = index_set[grid1_idx] - ind_mult[a][0]
                            tile_vert[grid2_idx] = index_set[grid2_idx] - ind_mult[a][1]
                            tile.append(tile_vert)
                        store.append(tile)
                    elif count > 0:
                        tile = self.n_gon(index_set, grid1_idx, grid2_idx, j, k, grid, list2, val)
                        p_store.append(tile)

        if len(store) > 0:
            store = np.dot(store, tile_vectors)
        
        ##this old method was a way of being able to store all the areas in one - which I don't think we necessarily need? 
        ##it's just lazy and can cause errors down the line
        # p_store = self.f(p_store, np.nan, dimension)
        # p_store = np.dot(p_store, tile_vectors)
        # p_store = [x[~np.isnan(x).all(axis=1)] for x in p_store]

        # tile_area = []
        # for a in range(len(p_store)):
        #     if len(p_store[a]) > 0:
        #         tile_area.append(self.polygon_area(p_store[a][:, 0], p_store[a][:, 1]))

        # for a in range(len(store)):
        #     tile_area.append(self.polygon_area(store[a][:, 0], store[a][:, 1]))

        

        poly_areas = []
        ngon_areas = []        
        ##calculate the areas of the 4-gons
        for a in range(len(store)):
            poly_areas.append(self.polygon_area(store[a][:, 0], store[a][:, 1]))

        #then the n-gons
        if len(p_store) > 0:
            
            ##this is necessary because you have a list of n-gons which may have different n's!
            #TODO: think - would a dictionary of different N's be useful? 6: [list of all 6-gons], 8: [list of all 8-ngons]?
            p_store = self.f(p_store, np.nan, dimension)
            p_store = np.dot(p_store, tile_vectors)
            p_store = [x[~np.isnan(x).all(axis=1)] for x in p_store]
            
            for a in range(len(p_store)):  
                if len(p_store[a]) > 0:
                    ngon_areas.append(self.polygon_area(p_store[a][:, 0], p_store[a][:, 1]))

        return store, p_store, poly_areas, ngon_areas

    def f(self, l, v, dimension):
        x = (2 + dimension) * 2
        return [(a + [[v] * dimension] * (x - len(a))) for a in l + [[]] * (x - len(l))]


class Grids:
    def __init__(self, vectors, line_len, grid_len, shifts, val):
        gen = self.line_generator(vectors, line_len, grid_len, shifts)
        self.grids = gen[0]
        self.index = gen[1]
        self.midpoints = gen[2]
        self.grid_vectors = vectors
        self.idx_min = np.min(self.index)
        self.idx_max = np.max(self.index)
        self.line_len = line_len
        self.grid_len = grid_len*2
        self.shifts = shifts
        self.val = val
        self.angles = [math.atan2(x[1],x[0]) for x in vectors]
        

    def perp_vec(self, v):
        #Returns the perpendicular vector
        return (v[1], -v[0])

    def line_generator(self, vectors, line_len, grid_len, shifts):
        store = []
        indices = []
        idx = list(range(-grid_len,grid_len))
        grid_len *= 2
        midpoints = []

        for a in range(len(vectors)):
            #take the vectors you want to use for grids 
            vec = vectors[a]
            #make perp to generate the actual line
            pvec = self.perp_vec(vec)

            #shift the sets of lines so that they're centered around zero

            centx = ((grid_len/2)*(vec[0]))
            centy = ((grid_len/2)*(vec[1]))

            #generate end points made by vectors, shifted by shifts (and centre), with line length defined by perp        
            end_p1 = [(((x+shifts[a])*vec[0]-centx + pvec[0]*line_len), ((x+shifts[a])*vec[1]-centy + pvec[1]*line_len)) for x in range(grid_len)]
            mid_p  = np.array([(end_p1[x][0] + vec[0]/2,end_p1[x][1]+ vec[1]/2) for x in range(grid_len)])
            end_p2 = [(((x+shifts[a])*vec[0]-centx - pvec[0]*line_len), ((x+shifts[a])*vec[1]-centy - pvec[1]*line_len)) for x in range(grid_len)]

            
            store.append([end_p1, end_p2])
            indices.append([idx[x] for x in range(grid_len)])

            midpoints.append(mid_p)
        return store, indices, midpoints

class tilePlot(pg.GraphicsObject):
    def __init__(self, tiling, poly_color, ngon_color):
        pg.GraphicsObject.__init__(self)

        self.generatePicture(tiling, poly_color, ngon_color)
    
    def generatePicture(self, tiling, poly_color, ngon_color):
        ## pre-computing a QPicture object allows paint() to run much more quickly, 
        ## rather than re-drawing the shapes every time.
        self.picture = QtGui.QPicture()
        p = QtGui.QPainter(self.picture)
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(pg.mkPen('k', width = 2))

        ##grab our tiles
        tiles = tiling.points
        ngons = tiling.p_points
        
        ##draw our tiles and n-gons, if they exist
        if len(ngon_color) != 0:
            for i in range(len(ngons)):
                polygon = QtGui.QPolygonF()
                ngon = ngons[i]
                if len(ngon) == 0:
                    continue
                p.setBrush(pg.mkBrush(ngon_color[i]))
                
                for j in range(len(ngon)):
                    x = ngon[j][0]
                    y = ngon[j][1]
                    polygon.append(QtCore.QPointF(x, y)) 
                p.drawPolygon(polygon)

        if len(poly_color) != 0:
            for i in range(len(tiles)):
                polygon = QtGui.QPolygonF()
                tile = tiles[i]
                p.setBrush(pg.mkBrush(poly_color[i]))
                for j in range(len(tile)):
                    x = tile[j][0]
                    y = tile[j][1]
                    polygon.append(QtCore.QPointF(x, y)) 
                p.drawPolygon(polygon)  
        p.end()

    
    def paint(self, p, *args):
        p.drawPicture(0, 0, self.picture)
       
    
    def boundingRect(self):
        ## boundingRect _must_ indicate the entire area that will be drawn on
        ## or else we will get artifacts and possibly crashing.
        ## (in this case, QPicture does all the work of computing the bouning rect for us)
        return QtCore.QRectF(self.picture.boundingRect())

class vectorPlotting(pg.GraphicsObject):

    #take in an argument of scale here, which is a list of scales according to the vector scale
    def __init__(self, fold):

        pg.GraphicsObject.__init__(self)

        theta = 2*np.pi/fold
        vectors = []
        #TODO: give a more appropriate scale (currently arbitrarily 30), and figure out what you want to do with 2-fold
        if fold > 2:
            for i in range(int(fold)):
                vectors.append((30*np.cos(theta*i), 30*np.sin(theta*i)))
        else:
            vectors.append((1, 0))
            vectors.append((0, 2))

        self.generatePicture(vectors)
    
    def generatePicture(self, vectors):
        ## pre-computing a QPicture object allows paint() to run much more quickly, 
        ## rather than re-drawing the shapes every time.
        self.picture = QtGui.QPicture()
        p = QtGui.QPainter(self.picture)
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(pg.mkPen('k', width = 2))
        p.setBrush(pg.mkBrush('k'))
        for i in range(len(vectors)):
            line = QtCore.QLineF(0,0,vectors[i][0],vectors[i][1])
            p.drawLine(line)
            ##draw a triangle
            triangle = []
            bearing = np.arctan2(vectors[i][1], vectors[i][0])

            p1x, p1y = vectors[i][0], vectors[i][1]
            p2x, p2y = vectors[i][0]+5*np.cos(bearing+np.radians(150)), vectors[i][1]+5*np.sin(bearing+np.radians(150))
            p3x, p3y = vectors[i][0]+5*np.cos(bearing-np.radians(150)), vectors[i][1]+5*np.sin(bearing-np.radians(150))

            triangle.append(QtCore.QPointF(p1x, p1y)) 
            triangle.append(QtCore.QPointF(p2x, p2y)) 
            triangle.append(QtCore.QPointF(p3x, p3y)) 
            p.drawPolygon(triangle)  

    
    def paint(self, p, *args):
        p.drawPicture(0, 0, self.picture)       
    
    def boundingRect(self):
        return QtCore.QRectF(self.picture.boundingRect())
    


if __name__ == "__main__":
    import sys
    ##start the app
    app = QtWidgets.QApplication(sys.argv)
    ##call our starting function
    MainWindow = QtWidgets.QMainWindow()
    #define our variable ui so we can add to things if necessary
    ui = Ui_MainWindow()
    ##such as setting up the mainwindow!
    ui.setupUi(MainWindow)
    
    
    ui.symmetryValue.setValue(5)
    vec_item = vectorPlotting(5)
    ui.vectorPlot.clear()
    ui.vectorPlot.enableAutoRange()
    ui.vectorPlot.addItem(vec_item) 
    ui.presetClick = True
    ui.sizeValue.setValue(10)
    ##finally, show the app, and wait for the user to close
    MainWindow.show()
    sys.exit(app.exec_())



