# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HyperTiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QDoubleValidator, QFont
import pyqtgraph as pg
import numpy as np
import itertools
import math
import colorsys
from scipy.spatial.distance import _distance_wrap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 800))
        screen = QtWidgets.QApplication.desktop().screenGeometry()
        center_x = (screen.width() - MainWindow.width()) // 2
        center_y = (screen.height() - MainWindow.height()) // 3
        MainWindow.move(center_x - 200, center_y)

        font = QFont()
        font.setPointSize(8)
        self.windows_open = {}

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parameterArea = QtWidgets.QFrame(self.centralwidget)
        self.parameterArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameterArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameterArea.setObjectName("parameterArea")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.parameterArea)
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.vectorPlot = pg.PlotWidget(self.parameterArea)
        self.vectorPlot.setObjectName("vectorPlot")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vectorPlot.sizePolicy().hasHeightForWidth())
        self.vectorPlot.setSizePolicy(sizePolicy)
        self.vectorPlot.setMinimumSize(QtCore.QSize(288, 288))
        self.vectorPlot.setMaximumSize(QtCore.QSize(288, 288))
        self.vectorPlot.setBackground('w')
        self.vectorPlot.getPlotItem().hideAxis('bottom')
        self.vectorPlot.getPlotItem().hideAxis('left')
        self.vectorPlot.hideButtons()
        self.verticalLayout_3.addWidget(self.vectorPlot)

        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem)

        self.tilingParameters = QtWidgets.QVBoxLayout()
        self.tilingParameters.setObjectName("tilingParameters")
        self.parameterGroup = QtWidgets.QGroupBox(self.parameterArea)
        self.parameterGroup.setObjectName("parameterGroup")
        self.parameterGroup.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.parameterGroup)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.gridShiftBox = QtWidgets.QHBoxLayout()
        self.gridShiftBox.setObjectName("gridShiftBox")
        self.shiftLabel = QtWidgets.QLabel(self.parameterGroup)
        self.shiftLabel.setObjectName("shiftLabel")
        self.gridShiftBox.addWidget(self.shiftLabel)
        self.shiftSelect = QtWidgets.QComboBox(self.parameterGroup)
        self.shiftSelect.setObjectName("shiftSelect")
        self.shiftSelect.addItem("Regular")
        self.shiftSelect.addItem("Zero")
        self.shiftSelect.addItem("Random")
        self.shiftSelect.addItem("Regular random")
        self.gridShiftBox.addWidget(self.shiftSelect)
        self.shiftSelect.setCurrentIndex(0)
        spacerItem5 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridShiftBox.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.gridShiftBox)
        self.shiftSelect.activated.connect(self.updateShift)

        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.symmetryBox = QtWidgets.QHBoxLayout()
        self.symmetryBox.setObjectName("symmetryBox")
        self.symmetryLabel = QtWidgets.QLabel(self.parameterGroup)
        self.symmetryLabel.setObjectName("symmetryLabel")
        self.symmetryBox.addWidget(self.symmetryLabel)
        self.symmetryValue = QtWidgets.QSpinBox(self.parameterGroup)
        self.symmetryValue.setObjectName("symmetryValue")
        self.symmetryBox.addWidget(self.symmetryValue)
        spacerItem3 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.symmetryBox.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.symmetryBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.symmetryValue.setSizePolicy(sizePolicy)
        self.symmetryValue.setMinimumSize(QtCore.QSize(60, 20))
        self.symmetryValue.setMaximumSize(QtCore.QSize(60, 20))
        self.symmetryValue.valueChanged.connect(self.updateVector)
        self.symmetryValue.setValue(5)
        self.symmetryValue.setMinimum(2)

        self.sizeBox = QtWidgets.QHBoxLayout()
        self.sizeBox.setObjectName("sizeBox")
        self.sizeLabel = QtWidgets.QLabel(self.parameterGroup)
        self.sizeLabel.setObjectName("sizeLabel")
        self.sizeBox.addWidget(self.sizeLabel)
        self.sizeValue = QtWidgets.QSpinBox(self.parameterGroup)
        self.sizeValue.setObjectName("sizeValue")
        self.sizeBox.addWidget(self.sizeValue)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.sizeBox.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.sizeBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.sizeValue.setSizePolicy(sizePolicy)
        self.sizeValue.setMinimumSize(QtCore.QSize(60, 20))
        self.sizeValue.setMaximumSize(QtCore.QSize(60, 20))
        self.sizeValue.setValue(10)

        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.advancedBox = QtWidgets.QHBoxLayout()
        self.advancedBox.setObjectName("advancedBox")
        self.advancedButton = QtWidgets.QPushButton(self.parameterGroup)
        self.advancedButton.setObjectName("advancedButton")
        self.advancedBox.addWidget(self.advancedButton)
        self.verticalLayout_4.addLayout(self.advancedBox)
        self.tilingParameters.addWidget(self.parameterGroup)

        self.advancedDock = QtWidgets.QDockWidget("Advanced Settings", MainWindow)
        self.advancedDock.setObjectName("advancedDock")
        self.advancedWindow = createAdvancedWindow()
        self.advancedDock.setWidget(self.advancedWindow)
        MainWindow.addDockWidget(QtCore.Qt.RightDockWidgetArea, self.advancedDock)
        self.advancedDock.hide()
        self.advancedButton.clicked.connect(self.toggleAdvancedDock)
        self.advancedButton.clicked.connect(self.advancedWindow.dataGrab)
        self.advancedDock.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable)
        self.original_size = MainWindow.size()
        self.advancedDock.setFloating(False)
        self.advancedDock.closeEvent = self.closeAdvancedDock

        self.advancedWindow.destroyed.connect(lambda: self.updateWindowState('advancedWindow'))
        self.symmetryValue.valueChanged.connect(self.advancedWindow.dataGrab)
        self.shiftSelect.activated.connect(self.advancedWindow.dataGrab)

        self.verticalLayout_3.addLayout(self.tilingParameters)
        self.tileButton = QtWidgets.QPushButton(self.parameterArea)
        self.tileButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.tileButton)
        self.tileButton.clicked.connect(self.generateTiling)

        spacerItem7 = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)

        self.horizontalLayout.addWidget(self.parameterArea)
        self.plotArea = QtWidgets.QFrame(self.centralwidget)
        self.plotArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotArea.setObjectName("plotArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plotArea)
        self.verticalLayout.setContentsMargins(7, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.tilingPlot = pg.PlotWidget(self.plotArea)
        self.tilingPlot.setObjectName("tilingPlot")
        self.verticalLayout.addWidget(self.tilingPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilingPlot.sizePolicy().hasHeightForWidth())
        self.tilingPlot.setSizePolicy(sizePolicy)
        self.tilingPlot.setMinimumSize(QtCore.QSize(700, 700))
        self.tilingPlot.setMaximumSize(QtCore.QSize(700, 700))
        self.tilingPlot.setBackground('w')
        self.tilingPlot.getPlotItem().hideAxis('bottom')
        self.tilingPlot.getPlotItem().hideAxis('left')
        self.tilingPlot.hideButtons()

        self.plotButtons = QtWidgets.QHBoxLayout()
        self.plotButtons.setSpacing(6)
        self.plotButtons.setObjectName("plotButtons")
        spacerItem8 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.plotButtons.addItem(spacerItem8)
        self.gridView = QtWidgets.QPushButton(self.plotArea)
        self.gridView.setObjectName("gridView")
        self.plotButtons.addWidget(self.gridView)
        self.editStyle = QtWidgets.QPushButton(self.plotArea)
        self.editStyle.clicked.connect(self.editTilingStyle)
        self.editStyle.setObjectName("editStyle")
        self.plotButtons.addWidget(self.editStyle)
        self.saveAs = QtWidgets.QPushButton(self.plotArea)
        self.saveAs.setObjectName("saveAs")
        self.plotButtons.addWidget(self.saveAs)
        self.verticalLayout.addLayout(self.plotButtons)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.plotArea)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.plotted = False

        self.vector_data = self.vectorSetup(5, self.shiftSelect.currentIndex())
        vec_item = vectorPlotting(self.vector_data)
        self.vectorPlot.clear()
        self.vectorPlot.enableAutoRange()
        self.vectorPlot.addItem(vec_item)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def toggleAdvancedDock(self):
        dock_width = self.advancedDock.sizeHint().width()
        if self.advancedDock.isVisible():
            self.advancedDock.hide()
            new_size = QtCore.QSize(self.original_size.width(), MainWindow.height())
            MainWindow.setMinimumSize(new_size)
            MainWindow.setMaximumSize(new_size)
            MainWindow.resize(new_size)
        else:
            self.advancedDock.show()
            new_width = self.original_size.width() + dock_width
            new_size = QtCore.QSize(new_width, MainWindow.height())
            MainWindow.setMinimumSize(new_size)
            MainWindow.setMaximumSize(new_size)
            MainWindow.resize(new_size)

    def closeAdvancedDock(self, event):
        new_size = QtCore.QSize(self.original_size.width(), MainWindow.height())
        MainWindow.setMinimumSize(new_size)
        MainWindow.setMaximumSize(new_size)
        MainWindow.resize(new_size)

    def updateWindowState(self, window_name):
        self.windows_open[window_name] = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.parameterGroup.setTitle(_translate("MainWindow", "Tiling parameters"))
        self.symmetryLabel.setText(_translate("MainWindow", "No. of vectors:"))
        self.sizeLabel.setText(_translate("MainWindow", "No. of grids:"))
        self.shiftLabel.setText(_translate("MainWindow", "Grid shifts:"))
        self.advancedButton.setText(_translate("MainWindow", "Advanced..."))
        self.tileButton.setText(_translate("MainWindow", "Tile!"))
        self.gridView.setText(_translate("MainWindow", "Grid view"))
        self.editStyle.setText(_translate("MainWindow", "Edit style..."))
        self.saveAs.setText(_translate("MainWindow", "Save as..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))

    def updateShift(self):
        shift_type = self.shiftSelect.currentIndex()
        fold = self.symmetryValue.value()
        shifts = []
        if shift_type == 0:
            if fold % 2 == 0:
                shifts = [1/(fold/2),-1/(fold/2)]*int(fold/2)
            else:
                shifts = [1/(fold)]*fold
        elif shift_type == 1:
            shifts = [0]*fold
        elif shift_type == 2:
            shifts = np.round(np.random.uniform(-1,1,fold),3)
        elif shift_type == 3:
            r = np.random.rand(1, fold)
            r /= np.sum(r)
            shifts = np.round(r[0],3)
        self.vector_data[:,3] = shifts

    def updateVector(self):
        value = self.symmetryValue.value()
        shiftSelect = self.shiftSelect.currentIndex()
        self.vector_data = self.vectorSetup(value, shiftSelect)
        vec_item = vectorPlotting(self.vector_data)
        self.vectorPlot.clear()
        self.vectorPlot.enableAutoRange()
        self.vectorPlot.addItem(vec_item)

        grid_vec_item = vectorPlotting(self.vector_data,'grid')
        self.advancedWindow.gridVectorPlot.clear()
        self.advancedWindow.gridVectorPlot.enableAutoRange()
        self.advancedWindow.gridVectorPlot.addItem(grid_vec_item)

    def editVector(self, data):
        vec_item = vectorPlotting(data)
        self.vectorPlot.clear()
        self.vectorPlot.enableAutoRange()
        self.vectorPlot.addItem(vec_item)

        grid_vec_item = vectorPlotting(data,'grid')
        self.advancedWindow.gridVectorPlot.clear()
        self.advancedWindow.gridVectorPlot.enableAutoRange()
        self.advancedWindow.gridVectorPlot.addItem(grid_vec_item)


    def vectorSetup(self, fold, shift_type):
        theta = 2*np.pi/fold
        grid_scale = [1] * fold
        tile_scale = [1] * fold
        shifts = []
        angle = []
        for i in range(int(fold)):
            angle.append(np.round(np.degrees(theta*i), 2))
        if shift_type == 0:
            if fold % 2 == 0:
                shifts = [1/(fold/2), -1/(fold/2)] * int(fold/2)
            else:
                shifts = [1/(fold)] * fold
        elif shift_type == 1:
            shifts = [0] * fold
        elif shift_type == 2:
            shifts = np.random.uniform(-1, 1, fold)
        elif shift_type == 3:
            r = np.random.rand(1, fold)
            r /= np.sum(r)
            shifts = r[0]
        return np.array(list(zip(grid_scale, tile_scale, angle, shifts)))

    def generateTiling(self):
        p5 = self.sizeValue.value()
        self.tiling = TileMaker(self.vector_data, p5)
        try:
            stack = np.vstack(self.tiling.points)
            xmax = np.max(stack[:, 0])
        except:
            xmax = np.max(np.vstack(self.tiling.p_points)[:, 0])
        self.tilingPlot.setLimits(xMin=-20, xMax=20, yMin=-20, yMax=20)
        self.poly_areas = np.round(self.tiling.poly_areas, 3)
        self.poly_unq = np.unique(self.poly_areas)
        for a in range(len(self.poly_unq)):
            self.poly_areas[self.poly_areas == self.poly_unq[a]] = a
        self.ngon_unq = []
        self.ngon_areas = self.tiling.ngon_areas
        if len(self.ngon_areas) > 0:
            self.ngon_areas = np.round(self.ngon_areas, 3)
            self.ngon_unq = np.unique(self.ngon_areas)
            for a in range(len(self.ngon_unq)):
                self.ngon_areas[self.ngon_areas == self.ngon_unq[a]] = a + len(self.poly_unq)
            self.ngon_areas = self.ngon_areas.astype(int)
        self.poly_areas = self.poly_areas.astype(int)
        color = []
        h = np.random.rand(1)[0]
        for a in range(len(self.poly_unq) + len(self.ngon_unq)):
            h += 0.618
            h %= 1
            (r, g, b) = colorsys.hsv_to_rgb(h, 0.4, 0.8)
            color.append((float(r*255), float(g*255), float(b*255)))
        poly_color = np.array(color)[self.poly_areas]
        ngon_color = np.array(color)[self.ngon_areas]
        item = tilePlot(self.tiling, poly_color, ngon_color)
        if self.plotted:
            self.tilingPlot.clear()
            self.tilingPlot.enableAutoRange()
        self.tilingPlot.addItem(item)
        self.plotted = True

    def editTilingStyle(self):

        if not self.plotted:
            return
        else:
            self.tilingPlot.clear()
            color = []
            h = np.random.rand(1)
            for a in range(len(self.poly_unq) + len(self.ngon_unq)):
                h += 0.618
                h %= 1
                (r, g, b) = colorsys.hsv_to_rgb(h, 0.4, 0.8)
                color.append((float(r*255), float(g*255), float(b*255)))
            poly_color = np.array(color)[self.poly_areas]
            ngon_color = np.array(color)[self.ngon_areas]
            item = tilePlot(self.tiling, poly_color, ngon_color)
            if self.plotted:
                self.tilingPlot.clear()
                self.tilingPlot.enableAutoRange()
            self.tilingPlot.addItem(item)
            self.plotted = True

class DecimalDelegate(QtWidgets.QStyledItemDelegate):
    def __init__(self, decimals=2, parent=None):
        super().__init__(parent)
        self.decimals = decimals

    def displayText(self, value, locale):
        try:
            return f"{float(value):.{self.decimals}f}"
        except (ValueError, TypeError):
            return str(value)

class TableModel(QtCore.QAbstractTableModel):
    def __init__(self, data, headers):
        super(TableModel, self).__init__()
        self._data = data
        self._headers = headers

    def data(self, index, role):
        if role == Qt.DisplayRole:
            value = self._data[index.row(), index.column()]
            return str(value)

    def rowCount(self, index):
        return self._data.shape[0]

    def columnCount(self, index):
        return self._data.shape[1]

    def headerData(self, section, orientation, role):
        if role == QtCore.Qt.DisplayRole:
            if orientation == QtCore.Qt.Horizontal:
                return self._headers[section]
            if orientation == QtCore.Qt.Vertical:
                return ['v'+ str(x+1) for x in range(len(self._data))][section]

    def insertRow(self, row, parent=QtCore.QModelIndex()):
        self.beginInsertRows(parent, row, row)
        self._data = np.insert(self._data, row, np.zeros(self.columnCount(parent)), axis=0)
        self.endInsertRows()

    def removeRow(self, row, parent=QtCore.QModelIndex()):
        self.beginRemoveRows(QtCore.QModelIndex(), row, row)
        self._data = np.delete(self._data, row, axis=0)
        self.endRemoveRows()

    def set_row_data(self, row, new_data, parent=QtCore.QModelIndex()):
        for col in range(self.columnCount(parent)):
            self.setData(self.index(row, col), new_data[col], QtCore.Qt.EditRole)

    def setData(self, index, value, role):
        if role == QtCore.Qt.EditRole:
            self._data[index.row(), index.column()] = value
            self.dataChanged.emit(index, index, (QtCore.Qt.DisplayRole,))
            return True
        return False

    def flags(self, index):
        return Qt.ItemIsSelectable | Qt.ItemIsEnabled | Qt.ItemIsEditable

class createAdvancedWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        ui.windows_open['advancedWindow'] = True

    def setupUi(self):
        self.resize(596, 418)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(0, 0))
        self.setMaximumSize(QtCore.QSize(10101010, 10101010))
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        validator = QDoubleValidator(-1e10, 1e10, 3)
        validator.setNotation(QDoubleValidator.StandardNotation)
        self.lineEdit.setValidator(validator)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        validator = QDoubleValidator(-1e10, 1e10, 3)
        validator.setNotation(QDoubleValidator.StandardNotation)
        self.lineEdit_2.setValidator(validator)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        validator = QDoubleValidator(0.0, 360., 2)
        validator.setNotation(QDoubleValidator.StandardNotation)
        self.lineEdit_3.setValidator(validator)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        validator = QDoubleValidator(-1e10, 1e10, 3)
        validator.setNotation(QDoubleValidator.StandardNotation)
        self.lineEdit_2.setValidator(validator)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        
        self.groupBox_2 = QtWidgets.QGroupBox(self)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.groupBox_2.setMinimumSize(QtCore.QSize(310, 320))
        self.groupBox_2.setMaximumSize(QtCore.QSize(310, 320))


        self.gridVectorPlot = pg.PlotWidget(self.groupBox_2)
        self.gridVectorPlot.setObjectName("gridVectorPlot")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.gridVectorPlot.sizePolicy().hasHeightForWidth())
        self.gridVectorPlot.setSizePolicy(sizePolicy)
        self.gridVectorPlot.setMinimumSize(QtCore.QSize(288, 288))
        self.gridVectorPlot.setMaximumSize(QtCore.QSize(288, 288))
        self.gridVectorPlot.setBackground('w')
        self.gridVectorPlot.getPlotItem().hideAxis('bottom')
        self.gridVectorPlot.getPlotItem().hideAxis('left')
        self.gridVectorPlot.hideButtons()
        self.verticalLayout_5.addWidget(self.gridVectorPlot)

        self.vector_data = ui.vector_data
        vec_item = vectorPlotting(self.vector_data, 'grid')
        self.gridVectorPlot.clear()
        self.gridVectorPlot.enableAutoRange()
        self.gridVectorPlot.addItem(vec_item)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()

        spacerItem1 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)

        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.on_new)
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_delete)
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(4, 3)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.lineEdits = [self.lineEdit, self.lineEdit_2, self.lineEdit_3, self.lineEdit_4]
        for col, lineEdit in enumerate(self.lineEdits):
            lineEdit.editingFinished.connect(lambda col=col, le=lineEdit: self.on_line_edit_finished(col, le))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Vector customisation"))
        self.label.setText(_translate("Form", "Tile scale:"))
        self.label_2.setText(_translate("Form", "Grid scale:"))
        self.label_3.setText(_translate("Form", "Angle:"))
        self.label_4.setText(_translate("Form", "Grid shift:"))
        self.groupBox_2.setTitle(_translate("Form", "Grid vectors"))
        # self.label_5.setText(_translate("Form", "Metallic ratios:"))
        # self.pushButton_3.setText(_translate("Form", "1.618..."))
        # self.pushButton_4.setText(_translate("Form", "2.414..."))
        # self.pushButton_5.setText(_translate("Form", "3.302..."))
        # self.pushButton_6.setText(_translate("Form", "4.236..."))
        # self.label_6.setText(_translate("Form", "Roots:"))
        # self.pushButton_7.setText(_translate("Form", "√2"))
        # self.pushButton_8.setText(_translate("Form", "√3"))
        # self.pushButton_9.setText(_translate("Form", "√5"))
        # self.pushButton_10.setText(_translate("Form", "√8"))
        # self.label_7.setText(_translate("Form", "Other:"))
        # self.pushButton_11.setText(_translate("Form", "π"))
        # self.pushButton_12.setText(_translate("Form", "e"))
        # self.label_8.setText(_translate("Form", "Custom:"))
        # self.pushButton_13.setText(_translate("Form", "Set"))
        self.pushButton_2.setText(_translate("Form", "New"))
        self.pushButton.setText(_translate("Form", "Delete"))

    def dataGrab(self):
        data = ui.vector_data
        self.model = TableModel(data, ['Tile scale', 'Grid scale', 'Angle', 'Grid shift'])
        self.tableView.setModel(self.model)
        self.tableView.verticalHeader().sectionClicked.connect(self.on_row_header_clicked)
        self.tableView.horizontalHeader().sectionClicked.connect(self.on_col_header_clicked)
        self.tableView.clicked.connect(self.on_cell_clicked)
        self.model.dataChanged.connect(self.on_cell_edited)
        self.tableView.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        decimal_delegate = DecimalDelegate(decimals=3)
        self.tableView.setItemDelegateForColumn(3, decimal_delegate)
        self.current_row = None

    def on_row_header_clicked(self, logicalIndex):
        self.current_row = logicalIndex
        row_data = [self.model.data(self.model.index(logicalIndex, col), QtCore.Qt.DisplayRole)
                    for col in range(self.model.columnCount(None))]
        for col, lineEdit in enumerate(self.lineEdits):
            lineEdit.setText(row_data[col])

    def on_col_header_clicked(self, logicalIndex):
        self.current_col = logicalIndex
        col_data = [self.model.data(self.model.index(logicalIndex, row), QtCore.Qt.DisplayRole)
                    for row in range(self.model.rowCount(None))]
        for col, lineEdit in enumerate(self.lineEdits):
            lineEdit.setText(col_data[col])

    def on_delete(self):
        row = self.tableView.selectedIndexes()[0].row()
        value = ui.symmetryValue.value() - 1
        shiftSelect = ui.shiftSelect.currentIndex()
        ui.symmetryValue.blockSignals(True)
        ui.symmetryValue.setValue(value)
        ui.symmetryValue.blockSignals(False)
        ui.vector_data = np.delete(ui.vector_data, row, axis=0)
        vec_item = vectorPlotting(ui.vector_data)
        ui.vectorPlot.clear()
        ui.vectorPlot.enableAutoRange()
        ui.vectorPlot.addItem(vec_item)


        vec_item = vectorPlotting(ui.vector_data, 'grid')
        self.gridVectorPlot.clear()
        self.gridVectorPlot.enableAutoRange()
        self.gridVectorPlot.addItem(vec_item)

        self.model.removeRow(row)

    def on_new(self):
        row = [1.0, 1.0, 0.0, 0.0]
        ui.vector_data = np.vstack([ui.vector_data, row])
        value = ui.symmetryValue.value() + 1
        row_index = self.model.rowCount(QtCore.QModelIndex())
        self.model.insertRow(row_index)
        self.model.set_row_data(row_index, row)
        ui.symmetryValue.blockSignals(True)
        ui.symmetryValue.setValue(value)
        ui.symmetryValue.blockSignals(False)
        vec_item = vectorPlotting(ui.vector_data)
        ui.vectorPlot.clear()
        ui.vectorPlot.enableAutoRange()
        ui.vectorPlot.addItem(vec_item)

    def on_cell_clicked(self, logicalIndex):
        col_data = [self.model.data(self.model.index(logicalIndex.row(), col), QtCore.Qt.DisplayRole)
                    for col in range(self.model.columnCount(None))]
        for col, lineEdit in enumerate(self.lineEdits):
            lineEdit.setText(col_data[col])

    def on_cell_edited(self, logicalIndex):
        col_data = [self.model.data(self.model.index(logicalIndex.row(), col), QtCore.Qt.DisplayRole)
                    for col in range(self.model.columnCount(None))]
        for col, lineEdit in enumerate(self.lineEdits):
            value = np.round(float(col_data[col]), 3)
            lineEdit.setText(str(value))
            ui.vector_data[logicalIndex.row()][col] = value
            ui.editVector(ui.vector_data)


    def on_line_edit_finished(self, col, lineEdit):
        current_row = self.tableView.currentIndex().row()
        value = lineEdit.text()
        index = self.model.index(current_row, col)
        self.model.setData(index, value, QtCore.Qt.EditRole)
        ui.vector_data[current_row][col] = value
        ui.editVector(ui.vector_data)

class TileMaker:
    def __init__(self, vector_data, grid_len):
        grid_vectors = []
        tile_vectors = []
        shifts = []
        for i in vector_data:
            tile_vectors.append((i[0]*np.cos(np.radians(i[2])),i[0]*np.sin(np.radians(i[2]))))
            grid_vectors.append((i[1]*np.cos(np.radians(i[2])),i[1]*np.sin(np.radians(i[2]))))
            shifts.append(i[3])
        ang = [math.atan2(x[1],x[0]) for x in grid_vectors]
        val = (np.round(ang,2)+0 >= 0).sum()
        ang = [(x+2*np.pi if np.round(x,2) < 0 else x) for x in ang]
        arg = np.argsort(ang)
        grid_vectors = np.array(grid_vectors)[arg]
        tile_vectors = np.array(tile_vectors)[arg]
        line_len = 100
        grid = Grids(grid_vectors, line_len, grid_len, shifts, val)
        gen = self.make_tile(grid, tile_vectors)
        self.points = gen[0]
        self.p_points = gen[1]
        self.poly_areas = gen[2]
        self.ngon_areas = gen[3]

    def intersect(self, A, B, C, D):
        t = ((A[0]-C[0])*(C[1]-D[1])-(A[1]-C[1])*(C[0]-D[0]))/((A[0]-B[0])*(C[1]-D[1])-(A[1]-B[1])*(C[0]-D[0]))
        u = ((A[0]-C[0])*(A[1]-B[1])-(A[1]-C[1])*(A[0]-B[0]))/((A[0]-B[0])*(C[1]-D[1])-(A[1]-B[1])*(C[0]-D[0]))
        if (t <= 1) & (t >= 0) & (u <= 1) & (u >= 0):
            return np.asarray([[A[0]+t*(B[0]-A[0]), A[1]+t*(B[1]-A[1])]])

    def cdist(self, XA, XB, dm):
        cdist_fn = getattr(_distance_wrap, "cdist_euclidean_double_wrap")
        cdist_fn(XA, XB, dm)
        return dm

    def collinear(self, comb_list, vectors):
        indexes = []
        for a in range(len(comb_list)):
            if np.cross(vectors[comb_list[a][0]], vectors[comb_list[a][1]]) == 0:
                indexes.append(a)
        self.del_list(comb_list, indexes)
        return comb_list

    def clockwise(self, coords):
        pp = (list(zip(coords[:,0], coords[:,1])))
        cent = (sum([p[0] for p in pp]) / len(pp), sum([p[1] for p in pp]) / len(pp))
        pp.sort(key=lambda p: math.atan2(p[1]-cent[1], p[0]-cent[0]))
        return pp

    def del_list(self, _list, indexes):
        for index in sorted(indexes, reverse=True):
            del _list[index]
        return _list

    def area(self, p):
        return 0.5 * abs(sum(x0 * y1 - x1 * y0 for ((x0, y0), (x1, y1)) in self.segments(p)))

    def polygon_area(self, x, y):
        correction = x[-1] * y[0] - y[-1] * x[0]
        main_area = np.dot(x[:-1], y[1:]) - np.dot(y[:-1], x[1:])
        return 0.5 * np.abs(main_area + correction)

    def segments(self, p):
        return zip(p, p[1:] + [p[0]])

    def perp_vec(self, v):
        return (v[1], -v[0])

    def cyclic(self, size):
        j, j_step = 0, 0
        i, i_step = 1, 1
        store = []
        for a in range(size):
            idx = list(range(j, i))
            store.append(idx)
            if a + 1 == size / 2:
                i_step = 0
                j_step = 1
            i += i_step
            j += j_step
        return store

    def n_gon(self, index_set, grid1_idx, grid2_idx, j, k, grid, list2, val):
        indices = grid.index[0]
        angles = [grid.angles[grid1_idx], grid.angles[grid2_idx]]
        vectors = [grid.grid_vectors[grid1_idx], grid.grid_vectors[grid2_idx]]
        factor = []
        all_grids = [grid1_idx, grid2_idx]
        if grid1_idx >= val:
            index_set[grid1_idx] = indices[j]
            angles[0] = angles[0] + math.pi
            vectors[0] = (-1 * vectors[0][0], -1 * vectors[0][1])
            factor.append(-1)
        else:
            index_set[grid1_idx] = indices[j - 1]
            factor.append(1)
        if grid2_idx >= val:
            index_set[grid2_idx] = indices[k]
            angles[1] = angles[1] + math.pi
            vectors[1] = (-1 * vectors[1][0], -1 * vectors[1][1])
            factor.append(-1)
        else:
            index_set[grid2_idx] = indices[k - 1]
            factor.append(1)
        construct = self.cyclic((2 + len(list2)) * 2)
        for i in range(len(list2)):
            grid_choice = list2[i][0]
            all_grids.append(grid_choice)
            if grid_choice >= val:
                index_set[grid_choice] = indices[max(list2[i][1], list2[i][2])]
                angles.append(grid.angles[grid_choice] + math.pi)
                vectors.append((-grid.grid_vectors[grid_choice][0], -grid.grid_vectors[grid_choice][1]))
                factor.append(-1)
            else:
                index_set[grid_choice] = indices[min(list2[i][1], list2[i][2])]
                angles.append(grid.angles[grid_choice])
                vectors.append(grid.grid_vectors[grid_choice])
                factor.append(1)
        origin = index_set.copy()
        ang_sort = np.argsort(angles)
        all_grids = np.array(all_grids)
        all_grids = all_grids[ang_sort]
        factor = np.array(factor)
        factor = factor[ang_sort]
        store = []
        store.append(origin)
        for i in range(len(construct) - 1):
            extend = origin.copy()
            for j in range(len(construct[i])):
                extend[all_grids[construct[i][j]]] = extend[all_grids[construct[i][j]]] + factor[construct[i][j]]
            store.append(extend)
        return store

    def make_tile(self, grid, tile_vectors):
        dm = np.empty((1, grid.grid_len), dtype=np.double)
        dimension = len(grid.grid_vectors)
        ind_mult = [[1, 0], [1, 1], [0, 1]]
        vec_no = list(range(dimension))
        radius = np.ceil(grid.grid_len / 3)
        val = grid.val
        combs = self.collinear(list(itertools.combinations(list(range(dimension)), 2)), grid.grid_vectors)
        store = []
        p_store = []
        indices = [0] * dimension
        for i in range(len(combs)):
            grid1_idx = combs[i][0]
            grid2_idx = combs[i][1]
            vec_query = self.del_list(vec_no.copy(), [grid1_idx, grid2_idx])
            for j in range(1, grid.grid_len):
                for k in range(1, grid.grid_len):
                    count = 0
                    interx = self.intersect(grid.grids[grid1_idx][0][j], grid.grids[grid1_idx][1][j], grid.grids[grid2_idx][0][k], grid.grids[grid2_idx][1][k])
                    if interx is None:
                        continue
                    if interx[0][0]**2 + interx[0][1]**2 > radius**2:
                        continue
                    tile = []
                    index_set = indices.copy()
                    index_set[grid1_idx] = grid.index[grid1_idx][j]
                    index_set[grid2_idx] = grid.index[grid2_idx][k]
                    list2 = []
                    for l in range(len(vec_query)):
                        grid_choice = vec_query[l]
                        dist = self.cdist(interx, grid.midpoints[grid_choice], dm)[0]
                        dist_idx = dist.argsort()
                        dist_sort = dist[dist_idx]
                        if dist_sort[1] - dist_sort[0] < 0.00000001:
                            count += 1
                            list2.append((grid_choice, dist_idx[0], dist_idx[1]))
                        else:
                            index_set[grid_choice] = grid.index[grid_choice][dist_idx[0]]
                    if count == 0:
                        tile.append(index_set)
                        for a in range(3):
                            tile_vert = index_set.copy()
                            tile_vert[grid1_idx] = index_set[grid1_idx] - ind_mult[a][0]
                            tile_vert[grid2_idx] = index_set[grid2_idx] - ind_mult[a][1]
                            tile.append(tile_vert)
                        store.append(tile)
                    elif count > 0:
                        tile = self.n_gon(index_set, grid1_idx, grid2_idx, j, k, grid, list2, val)
                        p_store.append(tile)
        if len(store) > 0:
            store = np.dot(store, tile_vectors)
        poly_areas = []
        ngon_areas = []
        for a in range(len(store)):
            poly_areas.append(self.polygon_area(store[a][:, 0], store[a][:, 1]))
        if len(p_store) > 0:
            p_store = self.f(p_store, np.nan, dimension)
            p_store = np.dot(p_store, tile_vectors)
            p_store = [x[~np.isnan(x).all(axis=1)] for x in p_store]
            for a in range(len(p_store)):
                if len(p_store[a]) > 0:
                    ngon_areas.append(self.polygon_area(p_store[a][:, 0], p_store[a][:, 1]))
        return store, p_store, poly_areas, ngon_areas

    def f(self, l, v, dimension):
        x = (2 + dimension) * 2
        return [(a + [[v] * dimension] * (x - len(a))) for a in l + [[]] * (x - len(l))]

class Grids:
    def __init__(self, vectors, line_len, grid_len, shifts, val):
        gen = self.line_generator(vectors, line_len, grid_len, shifts)
        self.grids = gen[0]
        self.index = gen[1]
        self.midpoints = gen[2]
        self.grid_vectors = vectors
        self.idx_min = np.min(self.index)
        self.idx_max = np.max(self.index)
        self.line_len = line_len
        self.grid_len = grid_len*2
        self.shifts = shifts
        self.val = val
        self.angles = [math.atan2(x[1],x[0]) for x in vectors]

    def perp_vec(self, v):
        return (v[1], -v[0])

    def line_generator(self, vectors, line_len, grid_len, shifts):
        store = []
        indices = []
        idx = list(range(-grid_len,grid_len))
        grid_len *= 2
        midpoints = []
        for a in range(len(vectors)):
            vec = vectors[a]
            pvec = self.perp_vec(vec)
            centx = ((grid_len/2)*(vec[0]))
            centy = ((grid_len/2)*(vec[1]))
            end_p1 = [(((x+shifts[a])*vec[0]-centx + pvec[0]*line_len), ((x+shifts[a])*vec[1]-centy + pvec[1]*line_len)) for x in range(grid_len)]
            mid_p  = np.array([(end_p1[x][0] + vec[0]/2,end_p1[x][1]+ vec[1]/2) for x in range(grid_len)])
            end_p2 = [(((x+shifts[a])*vec[0]-centx - pvec[0]*line_len), ((x+shifts[a])*vec[1]-centy - pvec[1]*line_len)) for x in range(grid_len)]
            store.append([end_p1, end_p2])
            indices.append([idx[x] for x in range(grid_len)])
            midpoints.append(mid_p)
        return store, indices, midpoints

class tilePlot(pg.GraphicsObject):
    def __init__(self, tiling, poly_color, ngon_color):
        pg.GraphicsObject.__init__(self)
        self.generatePicture(tiling, poly_color, ngon_color)

    def generatePicture(self, tiling, poly_color, ngon_color):
        self.picture = QtGui.QPicture()
        p = QtGui.QPainter(self.picture)
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(pg.mkPen('k', width=2))
        tiles = tiling.points
        ngons = tiling.p_points
        path = QtGui.QPainterPath()
        edge_path = QtGui.QPainterPath()
        for ngon, color in zip(ngons, ngon_color):
            if len(ngon) == 0:
                continue
            path.setFillRule(QtCore.Qt.WindingFill)
            path.addPolygon(QtGui.QPolygonF([QtCore.QPointF(x, y) for x, y in ngon]))
            p.fillPath(path, pg.mkBrush(color))
            for i in range(len(ngon)):
                next_i = (i + 1) % len(ngon)
                edge_path.moveTo(QtCore.QPointF(*ngon[i]))
                edge_path.lineTo(QtCore.QPointF(*ngon[next_i]))
            path.clear()
        for tile, color in zip(tiles, poly_color):
            path.setFillRule(QtCore.Qt.WindingFill)
            path.addPolygon(QtGui.QPolygonF([QtCore.QPointF(x, y) for x, y in tile]))
            p.fillPath(path, pg.mkBrush(color))
            for i in range(len(tile)):
                next_i = (i + 1) % len(tile)
                edge_path.moveTo(QtCore.QPointF(*tile[i]))
                edge_path.lineTo(QtCore.QPointF(*tile[next_i]))
            path.clear()
        p.drawPath(edge_path)
        p.end()

    def paint(self, p, *args):
        p.drawPicture(0, 0, self.picture)

    def boundingRect(self):
        return QtCore.QRectF(self.picture.boundingRect())

class vectorPlotting(pg.GraphicsObject):
    def __init__(self, vector_data, type = 'real'):
        pg.GraphicsObject.__init__(self)
        vectors = []
        if type == 'real':
            for i in vector_data:
                vectors.append((30*i[0]*np.cos(np.radians(i[2])),30*i[0]*np.sin(np.radians(i[2]))))
        else:
            for i in vector_data:
                vectors.append((30*i[1]*np.cos(np.radians(i[2])),30*i[1]*np.sin(np.radians(i[2]))))
        self.generatePicture(vectors)

    def generatePicture(self, vectors):
        self.picture = QtGui.QPicture()
        p = QtGui.QPainter(self.picture)
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(pg.mkPen('k', width=2))
        p.setBrush(pg.mkBrush('k'))
        for i in range(len(vectors)):
            line = QtCore.QLineF(0,0,vectors[i][0],vectors[i][1])
            p.drawLine(line)
            triangle = []
            bearing = np.arctan2(vectors[i][1], vectors[i][0])
            p1x, p1y = vectors[i][0], vectors[i][1]
            p2x, p2y = vectors[i][0]+5*np.cos(bearing+np.radians(150)), vectors[i][1]+5*np.sin(bearing+np.radians(150))
            p3x, p3y = vectors[i][0]+5*np.cos(bearing-np.radians(150)), vectors[i][1]+5*np.sin(bearing-np.radians(150))
            triangle.append(QtCore.QPointF(p1x, p1y))
            triangle.append(QtCore.QPointF(p2x, p2y))
            triangle.append(QtCore.QPointF(p3x, p3y))
            p.drawPolygon(triangle)

    def paint(self, p, *args):
        p.drawPicture(0, 0, self.picture)

    def boundingRect(self):
        return QtCore.QRectF(self.picture.boundingRect())

if __name__ == "__main__":
    import sys
    def closeAllWindows(self):
        for window_name, is_open in ui.windows_open.items():
            if is_open:
                getattr(ui, window_name).close()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.closeEvent = closeAllWindows
    MainWindow.show()
    sys.exit(app.exec_())



